### ISSUE TITLE
update tensorflow requirement

### ISSUE THREAD

**Issue by peterood** [nrlewis/nlpfromscratch-tf#1]
`pip install -r requirements.txt` returns 

`Could not find a version that satisfies the requirement tensorflow==1.0.1 (from -r requirements.txt (line 13)) (from versions: 0.12.1, 1.0.0, 1.1.0rc0)
No matching distribution found for tensorflow==1.0.1 (from -r requirements.txt (line 13))`

I updated requirements.txt to `tensorflow==1.1.0rc0`

**Comment by nrlewis** [comment]
Thanks!! updated requirements!
